openapi: 3.1.0
info:
  version: 1.0.0
  title: WalletFlow APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of WalletFlow App
tags:
  - name: Transactions
    description: Transactions operations.
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Auth operations.
servers:
  - url: https://moneydashboard-back.onrender.com
paths:
  /api/auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /api/auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /api/auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /api/users/current:
    get:
      $ref: ../swagger/paths/users/current.yaml
  /api/transaction-categories:
    get:
      $ref: ../swagger/paths/categories/api-transaction-categories.yaml
  /api/transactions:
    get:
      $ref: ../swagger/paths/transactions/get-api-transactions.yaml
    post:
      $ref: ../swagger/paths/transactions/post-api-transactions.yaml
  /api/transactions/{transactionId}:
    patch:
      $ref: ../swagger/paths/transactions/{transactionId}/patch-api-transactions.yaml
    delete:
      $ref: ../swagger/paths/transactions/{transactionId}/delete-api-transactions.yaml
  /api/transactions-summary/categories:
    get:
      $ref: ../swagger/paths/summary/transactions-summary-categories.yaml
  /api/transactions-summary-by-period:
    get:
      $ref: ../swagger/paths/summary/transactions-summary-by-period.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
